// <auto-generated />
using System;
using LeBataillon.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeBataillon.Database.Migrations
{
    [DbContext(typeof(LeBataillonDbContext))]
    [Migration("20200920182256_AddGame")]
    partial class AddGame
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeBataillon.Database.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GameDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamAttackerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamDefendantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameDateTime = new DateTime(2020, 9, 21, 14, 22, 55, 851, DateTimeKind.Local).AddTicks(1544),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 2,
                            GameDateTime = new DateTime(2020, 9, 22, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1557),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        },
                        new
                        {
                            Id = 3,
                            GameDateTime = new DateTime(2020, 9, 23, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1719),
                            TeamAttackerId = 7,
                            TeamDefendantId = 6
                        },
                        new
                        {
                            Id = 4,
                            GameDateTime = new DateTime(2020, 9, 24, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1758),
                            TeamAttackerId = 3,
                            TeamDefendantId = 2
                        },
                        new
                        {
                            Id = 5,
                            GameDateTime = new DateTime(2020, 9, 25, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1792),
                            TeamAttackerId = 6,
                            TeamDefendantId = 5
                        },
                        new
                        {
                            Id = 6,
                            GameDateTime = new DateTime(2020, 9, 26, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1829),
                            TeamAttackerId = 9,
                            TeamDefendantId = 8
                        },
                        new
                        {
                            Id = 7,
                            GameDateTime = new DateTime(2020, 9, 27, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1862),
                            TeamAttackerId = 5,
                            TeamDefendantId = 4
                        },
                        new
                        {
                            Id = 8,
                            GameDateTime = new DateTime(2020, 9, 28, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1896),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 9,
                            GameDateTime = new DateTime(2020, 9, 29, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1929),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        },
                        new
                        {
                            Id = 10,
                            GameDateTime = new DateTime(2020, 9, 30, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1961),
                            TeamAttackerId = 7,
                            TeamDefendantId = 6
                        },
                        new
                        {
                            Id = 11,
                            GameDateTime = new DateTime(2020, 10, 1, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(1992),
                            TeamAttackerId = 2,
                            TeamDefendantId = 1
                        },
                        new
                        {
                            Id = 12,
                            GameDateTime = new DateTime(2020, 10, 2, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2024),
                            TeamAttackerId = 6,
                            TeamDefendantId = 5
                        },
                        new
                        {
                            Id = 13,
                            GameDateTime = new DateTime(2020, 10, 3, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2059),
                            TeamAttackerId = 9,
                            TeamDefendantId = 8
                        },
                        new
                        {
                            Id = 14,
                            GameDateTime = new DateTime(2020, 10, 4, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2092),
                            TeamAttackerId = 5,
                            TeamDefendantId = 4
                        },
                        new
                        {
                            Id = 15,
                            GameDateTime = new DateTime(2020, 10, 5, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2169),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 16,
                            GameDateTime = new DateTime(2020, 10, 6, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2203),
                            TeamAttackerId = 3,
                            TeamDefendantId = 2
                        },
                        new
                        {
                            Id = 17,
                            GameDateTime = new DateTime(2020, 10, 7, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2234),
                            TeamAttackerId = 7,
                            TeamDefendantId = 6
                        },
                        new
                        {
                            Id = 18,
                            GameDateTime = new DateTime(2020, 10, 8, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2266),
                            TeamAttackerId = 2,
                            TeamDefendantId = 1
                        },
                        new
                        {
                            Id = 19,
                            GameDateTime = new DateTime(2020, 10, 9, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2298),
                            TeamAttackerId = 6,
                            TeamDefendantId = 5
                        },
                        new
                        {
                            Id = 20,
                            GameDateTime = new DateTime(2020, 10, 10, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2329),
                            TeamAttackerId = 9,
                            TeamDefendantId = 8
                        },
                        new
                        {
                            Id = 21,
                            GameDateTime = new DateTime(2020, 10, 11, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2361),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        },
                        new
                        {
                            Id = 22,
                            GameDateTime = new DateTime(2020, 10, 12, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2392),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 23,
                            GameDateTime = new DateTime(2020, 10, 13, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2423),
                            TeamAttackerId = 3,
                            TeamDefendantId = 2
                        },
                        new
                        {
                            Id = 24,
                            GameDateTime = new DateTime(2020, 10, 14, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2454),
                            TeamAttackerId = 7,
                            TeamDefendantId = 6
                        },
                        new
                        {
                            Id = 25,
                            GameDateTime = new DateTime(2020, 10, 15, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2484),
                            TeamAttackerId = 2,
                            TeamDefendantId = 1
                        },
                        new
                        {
                            Id = 26,
                            GameDateTime = new DateTime(2020, 10, 16, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2515),
                            TeamAttackerId = 5,
                            TeamDefendantId = 4
                        },
                        new
                        {
                            Id = 27,
                            GameDateTime = new DateTime(2020, 10, 17, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2548),
                            TeamAttackerId = 9,
                            TeamDefendantId = 8
                        },
                        new
                        {
                            Id = 28,
                            GameDateTime = new DateTime(2020, 10, 18, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2581),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        },
                        new
                        {
                            Id = 29,
                            GameDateTime = new DateTime(2020, 10, 19, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2692),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 30,
                            GameDateTime = new DateTime(2020, 10, 20, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2724),
                            TeamAttackerId = 3,
                            TeamDefendantId = 2
                        },
                        new
                        {
                            Id = 31,
                            GameDateTime = new DateTime(2020, 10, 21, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2757),
                            TeamAttackerId = 6,
                            TeamDefendantId = 5
                        },
                        new
                        {
                            Id = 32,
                            GameDateTime = new DateTime(2020, 10, 22, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2788),
                            TeamAttackerId = 2,
                            TeamDefendantId = 1
                        },
                        new
                        {
                            Id = 33,
                            GameDateTime = new DateTime(2020, 10, 23, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2820),
                            TeamAttackerId = 5,
                            TeamDefendantId = 4
                        },
                        new
                        {
                            Id = 34,
                            GameDateTime = new DateTime(2020, 10, 24, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2853),
                            TeamAttackerId = 9,
                            TeamDefendantId = 8
                        },
                        new
                        {
                            Id = 35,
                            GameDateTime = new DateTime(2020, 10, 25, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2884),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        },
                        new
                        {
                            Id = 36,
                            GameDateTime = new DateTime(2020, 10, 26, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2913),
                            TeamAttackerId = 7,
                            TeamDefendantId = 6
                        },
                        new
                        {
                            Id = 37,
                            GameDateTime = new DateTime(2020, 10, 27, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2943),
                            TeamAttackerId = 3,
                            TeamDefendantId = 2
                        },
                        new
                        {
                            Id = 38,
                            GameDateTime = new DateTime(2020, 10, 28, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(2974),
                            TeamAttackerId = 6,
                            TeamDefendantId = 5
                        },
                        new
                        {
                            Id = 39,
                            GameDateTime = new DateTime(2020, 10, 29, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3006),
                            TeamAttackerId = 2,
                            TeamDefendantId = 1
                        },
                        new
                        {
                            Id = 40,
                            GameDateTime = new DateTime(2020, 10, 30, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3037),
                            TeamAttackerId = 5,
                            TeamDefendantId = 4
                        },
                        new
                        {
                            Id = 41,
                            GameDateTime = new DateTime(2020, 10, 31, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3100),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 42,
                            GameDateTime = new DateTime(2020, 11, 1, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3134),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        },
                        new
                        {
                            Id = 43,
                            GameDateTime = new DateTime(2020, 11, 2, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3164),
                            TeamAttackerId = 7,
                            TeamDefendantId = 6
                        },
                        new
                        {
                            Id = 44,
                            GameDateTime = new DateTime(2020, 11, 3, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3195),
                            TeamAttackerId = 3,
                            TeamDefendantId = 2
                        },
                        new
                        {
                            Id = 45,
                            GameDateTime = new DateTime(2020, 11, 4, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3226),
                            TeamAttackerId = 6,
                            TeamDefendantId = 5
                        },
                        new
                        {
                            Id = 46,
                            GameDateTime = new DateTime(2020, 11, 5, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3257),
                            TeamAttackerId = 9,
                            TeamDefendantId = 8
                        },
                        new
                        {
                            Id = 47,
                            GameDateTime = new DateTime(2020, 11, 6, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3289),
                            TeamAttackerId = 5,
                            TeamDefendantId = 4
                        },
                        new
                        {
                            Id = 48,
                            GameDateTime = new DateTime(2020, 11, 7, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3318),
                            TeamAttackerId = 8,
                            TeamDefendantId = 7
                        },
                        new
                        {
                            Id = 49,
                            GameDateTime = new DateTime(2020, 11, 8, 14, 22, 55, 854, DateTimeKind.Local).AddTicks(3348),
                            TeamAttackerId = 4,
                            TeamDefendantId = 3
                        });
                });

            modelBuilder.Entity("LeBataillon.Database.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Adrian@bataillonMail.com",
                            FirstName = "Adrian",
                            LastName = "Jonkruojis",
                            Level = 0,
                            NickName = "AdrianAlias",
                            PhoneNumber = "214-764-3816"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Krissy@bataillonMail.com",
                            FirstName = "Krissy",
                            LastName = "Reidcoln",
                            Level = 0,
                            NickName = "KrissyAlias",
                            PhoneNumber = "742-813-7421"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Pat@bataillonMail.com",
                            FirstName = "Pat",
                            LastName = "Steinstrand",
                            Level = 0,
                            NickName = "PatAlias",
                            PhoneNumber = "367-252-3834"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Palmira@bataillonMail.com",
                            FirstName = "Palmira",
                            LastName = "Nuugaatrapaluk",
                            Level = 0,
                            NickName = "PalmiraAlias",
                            PhoneNumber = "785-411-6446"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Ralph@bataillonMail.com",
                            FirstName = "Ralph",
                            LastName = "Vadtälje",
                            Level = 0,
                            NickName = "RalphAlias",
                            PhoneNumber = "333-648-2851"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Arielle@bataillonMail.com",
                            FirstName = "Arielle",
                            LastName = "Eqalunavik",
                            Level = 0,
                            NickName = "ArielleAlias",
                            PhoneNumber = "758-787-5464"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Troy@bataillonMail.com",
                            FirstName = "Troy",
                            LastName = "Lystrup",
                            Level = 0,
                            NickName = "TroyAlias",
                            PhoneNumber = "476-136-1877"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Marcell@bataillonMail.com",
                            FirstName = "Marcell",
                            LastName = "Ixtatla",
                            Level = 0,
                            NickName = "MarcellAlias",
                            PhoneNumber = "823-375-4482"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Vi@bataillonMail.com",
                            FirstName = "Vi",
                            LastName = "Haapsa",
                            Level = 0,
                            NickName = "ViAlias",
                            PhoneNumber = "441-434-8815"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Sherise@bataillonMail.com",
                            FirstName = "Sherise",
                            LastName = "Guasabaro",
                            Level = 0,
                            NickName = "SheriseAlias",
                            PhoneNumber = "877-663-4428"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Angelina@bataillonMail.com",
                            FirstName = "Angelina",
                            LastName = "Kalatee",
                            Level = 0,
                            NickName = "AngelinaAlias",
                            PhoneNumber = "414-822-7833"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Liliana@bataillonMail.com",
                            FirstName = "Liliana",
                            LastName = "Boswood",
                            Level = 0,
                            NickName = "LilianaAlias",
                            PhoneNumber = "832-151-3446"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Sheryl@bataillonMail.com",
                            FirstName = "Sheryl",
                            LastName = "Hókrókur",
                            Level = 0,
                            NickName = "SherylAlias",
                            PhoneNumber = "567-318-6851"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Mariella@bataillonMail.com",
                            FirstName = "Mariella",
                            LastName = "Dragstrup",
                            Level = 0,
                            NickName = "MariellaAlias",
                            PhoneNumber = "185-557-2464"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Berniece@bataillonMail.com",
                            FirstName = "Berniece",
                            LastName = "Ketne",
                            Level = 0,
                            NickName = "BernieceAlias",
                            PhoneNumber = "523-786-6877"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Conrad@bataillonMail.com",
                            FirstName = "Conrad",
                            LastName = "Kalvee",
                            Level = 0,
                            NickName = "ConradAlias",
                            PhoneNumber = "158-845-1482"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Sherlene@bataillonMail.com",
                            FirstName = "Sherlene",
                            LastName = "Kedainkai",
                            Level = 0,
                            NickName = "SherleneAlias",
                            PhoneNumber = "576-284-5815"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Nicholas@bataillonMail.com",
                            FirstName = "Nicholas",
                            LastName = "Rovanola",
                            Level = 0,
                            NickName = "NicholasAlias",
                            PhoneNumber = "213-433-8428"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Tyson@bataillonMail.com",
                            FirstName = "Tyson",
                            LastName = "Brønnøyden",
                            Level = 0,
                            NickName = "TysonAlias",
                            PhoneNumber = "641-572-4833"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Derick@bataillonMail.com",
                            FirstName = "Derick",
                            LastName = "Ísafholt",
                            Level = 0,
                            NickName = "DerickAlias",
                            PhoneNumber = "266-721-7446"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Leida@bataillonMail.com",
                            FirstName = "Leida",
                            LastName = "Hammervåg",
                            Level = 0,
                            NickName = "LeidaAlias",
                            PhoneNumber = "684-168-3851"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Debi@bataillonMail.com",
                            FirstName = "Debi",
                            LastName = "Kulli",
                            Level = 0,
                            NickName = "DebiAlias",
                            PhoneNumber = "232-327-7464"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Ernestine@bataillonMail.com",
                            FirstName = "Ernestine",
                            LastName = "Enbo",
                            Level = 0,
                            NickName = "ErnestineAlias",
                            PhoneNumber = "657-456-2877"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Adrian@bataillonMail.com",
                            FirstName = "Adrian",
                            LastName = "Lazmerge",
                            Level = 0,
                            NickName = "AdrianAlias",
                            PhoneNumber = "375-615-6481"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Eugenie@bataillonMail.com",
                            FirstName = "Eugenie",
                            LastName = "Reidcoln",
                            Level = 0,
                            NickName = "EugenieAlias",
                            PhoneNumber = "722-844-1814"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Cathryn@bataillonMail.com",
                            FirstName = "Cathryn",
                            LastName = "Breksos",
                            Level = 0,
                            NickName = "CathrynAlias",
                            PhoneNumber = "348-183-5427"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Jamal@bataillonMail.com",
                            FirstName = "Jamal",
                            LastName = "Nuugaatrapaluk",
                            Level = 0,
                            NickName = "JamalAlias",
                            PhoneNumber = "766-342-1832"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Emely@bataillonMail.com",
                            FirstName = "Emely",
                            LastName = "Norrviken",
                            Level = 0,
                            NickName = "EmelyAlias",
                            PhoneNumber = "313-571-4445"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Arielle@bataillonMail.com",
                            FirstName = "Arielle",
                            LastName = "Eqalunavik",
                            Level = 0,
                            NickName = "ArielleAlias",
                            PhoneNumber = "831-638-8858"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Steven@bataillonMail.com",
                            FirstName = "Steven",
                            LastName = "Ulhus",
                            Level = 0,
                            NickName = "StevenAlias",
                            PhoneNumber = "456-877-3463"
                        },
                        new
                        {
                            Id = 31,
                            Email = "Roma@bataillonMail.com",
                            FirstName = "Roma",
                            LastName = "Apatcruz",
                            Level = 0,
                            NickName = "RomaAlias",
                            PhoneNumber = "884-226-7876"
                        },
                        new
                        {
                            Id = 32,
                            Email = "Simonne@bataillonMail.com",
                            FirstName = "Simonne",
                            LastName = "Mõisali",
                            Level = 0,
                            NickName = "SimonneAlias",
                            PhoneNumber = "422-465-2481"
                        },
                        new
                        {
                            Id = 33,
                            Email = "Jeanetta@bataillonMail.com",
                            FirstName = "Jeanetta",
                            LastName = "Mensmere",
                            Level = 0,
                            NickName = "JeanettaAlias",
                            PhoneNumber = "857-514-6814"
                        },
                        new
                        {
                            Id = 34,
                            Email = "Angelina@bataillonMail.com",
                            FirstName = "Angelina",
                            LastName = "Nittinen",
                            Level = 0,
                            NickName = "AngelinaAlias",
                            PhoneNumber = "475-753-2427"
                        },
                        new
                        {
                            Id = 35,
                            Email = "Magen@bataillonMail.com",
                            FirstName = "Magen",
                            LastName = "Albro",
                            Level = 0,
                            NickName = "MagenAlias",
                            PhoneNumber = "112-112-5132"
                        },
                        new
                        {
                            Id = 36,
                            Email = "Jane@bataillonMail.com",
                            FirstName = "Jane",
                            LastName = "Hókrókur",
                            Level = 0,
                            NickName = "JaneAlias",
                            PhoneNumber = "548-241-1545"
                        },
                        new
                        {
                            Id = 37,
                            Email = "Tonita@bataillonMail.com",
                            FirstName = "Tonita",
                            LastName = "Loktu",
                            Level = 0,
                            NickName = "TonitaAlias",
                            PhoneNumber = "166-488-4158"
                        },
                        new
                        {
                            Id = 38,
                            Email = "Dina@bataillonMail.com",
                            FirstName = "Dina",
                            LastName = "Ketne",
                            Level = 0,
                            NickName = "DinaAlias",
                            PhoneNumber = "583-637-8563"
                        },
                        new
                        {
                            Id = 39,
                            Email = "Conrad@bataillonMail.com",
                            FirstName = "Conrad",
                            LastName = "Siukoski",
                            Level = 0,
                            NickName = "ConradAlias",
                            PhoneNumber = "131-876-4176"
                        },
                        new
                        {
                            Id = 40,
                            Email = "Adell@bataillonMail.com",
                            FirstName = "Adell",
                            LastName = "Kedainkai",
                            Level = 0,
                            NickName = "AdellAlias",
                            PhoneNumber = "556-135-7581"
                        },
                        new
                        {
                            Id = 41,
                            Email = "Pierre@bataillonMail.com",
                            FirstName = "Pierre",
                            LastName = "Akssandur",
                            Level = 0,
                            NickName = "PierreAlias",
                            PhoneNumber = "274-364-3114"
                        },
                        new
                        {
                            Id = 42,
                            Email = "Bianca@bataillonMail.com",
                            FirstName = "Bianca",
                            LastName = "Brønnøyden",
                            Level = 0,
                            NickName = "BiancaAlias",
                            PhoneNumber = "622-523-6527"
                        },
                        new
                        {
                            Id = 43,
                            Email = "Barbie@bataillonMail.com",
                            FirstName = "Barbie",
                            LastName = "Jaunli",
                            Level = 0,
                            NickName = "BarbieAlias",
                            PhoneNumber = "247-652-2132"
                        },
                        new
                        {
                            Id = 44,
                            Email = "Leida@bataillonMail.com",
                            FirstName = "Leida",
                            LastName = "Kungstuna",
                            Level = 0,
                            NickName = "LeidaAlias",
                            PhoneNumber = "665-811-5544"
                        },
                        new
                        {
                            Id = 45,
                            Email = "Rosetta@bataillonMail.com",
                            FirstName = "Rosetta",
                            LastName = "Jonkruojis",
                            Level = 0,
                            NickName = "RosettaAlias",
                            PhoneNumber = "212-258-1157"
                        },
                        new
                        {
                            Id = 46,
                            Email = "Krissy@bataillonMail.com",
                            FirstName = "Krissy",
                            LastName = "Clarehurst",
                            Level = 0,
                            NickName = "KrissyAlias",
                            PhoneNumber = "738-487-5562"
                        },
                        new
                        {
                            Id = 47,
                            Email = "Marlon@bataillonMail.com",
                            FirstName = "Marlon",
                            LastName = "Steinstrand",
                            Level = 0,
                            NickName = "MarlonAlias",
                            PhoneNumber = "355-546-8175"
                        },
                        new
                        {
                            Id = 48,
                            Email = "Palmira@bataillonMail.com",
                            FirstName = "Palmira",
                            LastName = "Flatwood",
                            Level = 0,
                            NickName = "PalmiraAlias",
                            PhoneNumber = "783-785-4588"
                        },
                        new
                        {
                            Id = 49,
                            Email = "Cathryn@bataillonMail.com",
                            FirstName = "Cathryn",
                            LastName = "Breksos",
                            Level = 0,
                            NickName = "CathrynAlias",
                            PhoneNumber = "321-134-7113"
                        },
                        new
                        {
                            Id = 50,
                            Email = "Eugenio@bataillonMail.com",
                            FirstName = "Eugenio",
                            LastName = "Uummanqaq",
                            Level = 0,
                            NickName = "EugenioAlias",
                            PhoneNumber = "746-273-3526"
                        },
                        new
                        {
                            Id = 51,
                            Email = "Troy@bataillonMail.com",
                            FirstName = "Troy",
                            LastName = "Norrviken",
                            Level = 0,
                            NickName = "TroyAlias",
                            PhoneNumber = "374-422-7131"
                        },
                        new
                        {
                            Id = 52,
                            Email = "Tad@bataillonMail.com",
                            FirstName = "Tad",
                            LastName = "Ixtatla",
                            Level = 0,
                            NickName = "TadAlias",
                            PhoneNumber = "811-661-2544"
                        },
                        new
                        {
                            Id = 53,
                            Email = "Vi@bataillonMail.com",
                            FirstName = "Vi",
                            LastName = "Ulhus",
                            Level = 0,
                            NickName = "ViAlias",
                            PhoneNumber = "437-728-6157"
                        },
                        new
                        {
                            Id = 54,
                            Email = "Roma@bataillonMail.com",
                            FirstName = "Roma",
                            LastName = "Guasabaro",
                            Level = 0,
                            NickName = "RomaAlias",
                            PhoneNumber = "865-156-1562"
                        },
                        new
                        {
                            Id = 55,
                            Email = "Alejandro@bataillonMail.com",
                            FirstName = "Alejandro",
                            LastName = "Mõisali",
                            Level = 0,
                            NickName = "AlejandroAlias",
                            PhoneNumber = "482-315-5175"
                        },
                        new
                        {
                            Id = 56,
                            Email = "Liliana@bataillonMail.com",
                            FirstName = "Liliana",
                            LastName = "Boswood",
                            Level = 0,
                            NickName = "LilianaAlias",
                            PhoneNumber = "828-544-8588"
                        },
                        new
                        {
                            Id = 57,
                            Email = "Marcie@bataillonMail.com",
                            FirstName = "Marcie",
                            LastName = "Nittinen",
                            Level = 0,
                            NickName = "MarcieAlias",
                            PhoneNumber = "555-683-4113"
                        },
                        new
                        {
                            Id = 58,
                            Email = "Mariella@bataillonMail.com",
                            FirstName = "Mariella",
                            LastName = "Dragstrup",
                            Level = 0,
                            NickName = "MariellaAlias",
                            PhoneNumber = "173-842-8526"
                        },
                        new
                        {
                            Id = 59,
                            Email = "Jane@bataillonMail.com",
                            FirstName = "Jane",
                            LastName = "Ólafsholt",
                            Level = 0,
                            NickName = "JaneAlias",
                            PhoneNumber = "521-271-3131"
                        },
                        new
                        {
                            Id = 60,
                            Email = "Marcella@bataillonMail.com",
                            FirstName = "Marcella",
                            LastName = "Kalvee",
                            Level = 0,
                            NickName = "MarcellaAlias",
                            PhoneNumber = "146-338-7544"
                        },
                        new
                        {
                            Id = 61,
                            Email = "Sherlene@bataillonMail.com",
                            FirstName = "Sherlene",
                            LastName = "Salkile",
                            Level = 0,
                            NickName = "SherleneAlias",
                            PhoneNumber = "564-567-2157"
                        },
                        new
                        {
                            Id = 62,
                            Email = "Antonetta@bataillonMail.com",
                            FirstName = "Antonetta",
                            LastName = "Rovanola",
                            Level = 0,
                            NickName = "AntonettaAlias",
                            PhoneNumber = "111-726-6562"
                        },
                        new
                        {
                            Id = 63,
                            Email = "Tyson@bataillonMail.com",
                            FirstName = "Tyson",
                            LastName = "Balniai",
                            Level = 0,
                            NickName = "TysonAlias",
                            PhoneNumber = "637-165-2175"
                        },
                        new
                        {
                            Id = 64,
                            Email = "Pierre@bataillonMail.com",
                            FirstName = "Pierre",
                            LastName = "Akssandur",
                            Level = 0,
                            NickName = "PierreAlias",
                            PhoneNumber = "255-214-5587"
                        },
                        new
                        {
                            Id = 65,
                            Email = "Sheridan@bataillonMail.com",
                            FirstName = "Sheridan",
                            LastName = "Hammervåg",
                            Level = 0,
                            NickName = "SheridanAlias",
                            PhoneNumber = "682-453-1112"
                        },
                        new
                        {
                            Id = 66,
                            Email = "Debi@bataillonMail.com",
                            FirstName = "Debi",
                            LastName = "Jaunli",
                            Level = 0,
                            NickName = "DebiAlias",
                            PhoneNumber = "228-612-4525"
                        },
                        new
                        {
                            Id = 67,
                            Email = "Johana@bataillonMail.com",
                            FirstName = "Johana",
                            LastName = "Enbo",
                            Level = 0,
                            NickName = "JohanaAlias",
                            PhoneNumber = "645-741-8138"
                        },
                        new
                        {
                            Id = 68,
                            Email = "Adrian@bataillonMail.com",
                            FirstName = "Adrian",
                            LastName = "Jonkruojis",
                            Level = 0,
                            NickName = "AdrianAlias",
                            PhoneNumber = "373-188-3543"
                        },
                        new
                        {
                            Id = 69,
                            Email = "Krissy@bataillonMail.com",
                            FirstName = "Krissy",
                            LastName = "Reidcoln",
                            Level = 0,
                            NickName = "KrissyAlias",
                            PhoneNumber = "718-337-7156"
                        },
                        new
                        {
                            Id = 70,
                            Email = "Pat@bataillonMail.com",
                            FirstName = "Pat",
                            LastName = "Steinstrand",
                            Level = 0,
                            NickName = "PatAlias",
                            PhoneNumber = "336-476-3561"
                        },
                        new
                        {
                            Id = 71,
                            Email = "Jamal@bataillonMail.com",
                            FirstName = "Jamal",
                            LastName = "Nuugaatrapaluk",
                            Level = 0,
                            NickName = "JamalAlias",
                            PhoneNumber = "764-635-6174"
                        },
                        new
                        {
                            Id = 72,
                            Email = "Ralph@bataillonMail.com",
                            FirstName = "Ralph",
                            LastName = "Vadtälje",
                            Level = 0,
                            NickName = "RalphAlias",
                            PhoneNumber = "381-864-2587"
                        },
                        new
                        {
                            Id = 73,
                            Email = "Arielle@bataillonMail.com",
                            FirstName = "Arielle",
                            LastName = "Eqalunavik",
                            Level = 0,
                            NickName = "ArielleAlias",
                            PhoneNumber = "727-223-5112"
                        },
                        new
                        {
                            Id = 74,
                            Email = "Troy@bataillonMail.com",
                            FirstName = "Troy",
                            LastName = "Lystrup",
                            Level = 0,
                            NickName = "TroyAlias",
                            PhoneNumber = "454-352-1525"
                        },
                        new
                        {
                            Id = 75,
                            Email = "Marcell@bataillonMail.com",
                            FirstName = "Marcell",
                            LastName = "Apatcruz",
                            Level = 0,
                            NickName = "MarcellAlias",
                            PhoneNumber = "872-511-5138"
                        },
                        new
                        {
                            Id = 76,
                            Email = "Simonne@bataillonMail.com",
                            FirstName = "Simonne",
                            LastName = "Haapsa",
                            Level = 0,
                            NickName = "SimonneAlias",
                            PhoneNumber = "418-758-8543"
                        },
                        new
                        {
                            Id = 77,
                            Email = "Sherise@bataillonMail.com",
                            FirstName = "Sherise",
                            LastName = "Guasabaro",
                            Level = 0,
                            NickName = "SheriseAlias",
                            PhoneNumber = "845-887-4156"
                        },
                        new
                        {
                            Id = 78,
                            Email = "Angelina@bataillonMail.com",
                            FirstName = "Angelina",
                            LastName = "Kalatee",
                            Level = 0,
                            NickName = "AngelinaAlias",
                            PhoneNumber = "463-246-7561"
                        },
                        new
                        {
                            Id = 79,
                            Email = "Liliana@bataillonMail.com",
                            FirstName = "Liliana",
                            LastName = "Boswood",
                            Level = 0,
                            NickName = "LilianaAlias",
                            PhoneNumber = "888-475-3174"
                        },
                        new
                        {
                            Id = 80,
                            Email = "Sheryl@bataillonMail.com",
                            FirstName = "Sheryl",
                            LastName = "Hókrókur",
                            Level = 0,
                            NickName = "SherylAlias",
                            PhoneNumber = "536-634-7577"
                        },
                        new
                        {
                            Id = 81,
                            Email = "Tonita@bataillonMail.com",
                            FirstName = "Tonita",
                            LastName = "Dragstrup",
                            Level = 0,
                            NickName = "TonitaAlias",
                            PhoneNumber = "154-773-2182"
                        },
                        new
                        {
                            Id = 82,
                            Email = "Berniece@bataillonMail.com",
                            FirstName = "Berniece",
                            LastName = "Ketne",
                            Level = 0,
                            NickName = "BernieceAlias",
                            PhoneNumber = "581-122-6515"
                        },
                        new
                        {
                            Id = 83,
                            Email = "Conrad@bataillonMail.com",
                            FirstName = "Conrad",
                            LastName = "Kalvee",
                            Level = 0,
                            NickName = "ConradAlias",
                            PhoneNumber = "127-361-1128"
                        },
                        new
                        {
                            Id = 84,
                            Email = "Sherlene@bataillonMail.com",
                            FirstName = "Sherlene",
                            LastName = "Kedainkai",
                            Level = 0,
                            NickName = "SherleneAlias",
                            PhoneNumber = "544-428-5532"
                        },
                        new
                        {
                            Id = 85,
                            Email = "Nicholas@bataillonMail.com",
                            FirstName = "Nicholas",
                            LastName = "Rovanola",
                            Level = 0,
                            NickName = "NicholasAlias",
                            PhoneNumber = "272-657-8145"
                        },
                        new
                        {
                            Id = 86,
                            Email = "Bianca@bataillonMail.com",
                            FirstName = "Bianca",
                            LastName = "Brønnøyden",
                            Level = 0,
                            NickName = "BiancaAlias",
                            PhoneNumber = "618-816-4558"
                        },
                        new
                        {
                            Id = 87,
                            Email = "Derick@bataillonMail.com",
                            FirstName = "Derick",
                            LastName = "Ísafholt",
                            Level = 0,
                            NickName = "DerickAlias",
                            PhoneNumber = "235-245-8163"
                        },
                        new
                        {
                            Id = 88,
                            Email = "Leida@bataillonMail.com",
                            FirstName = "Leida",
                            LastName = "Kungstuna",
                            Level = 0,
                            NickName = "LeidaAlias",
                            PhoneNumber = "663-384-3576"
                        },
                        new
                        {
                            Id = 89,
                            Email = "Debi@bataillonMail.com",
                            FirstName = "Debi",
                            LastName = "Kulli",
                            Level = 0,
                            NickName = "DebiAlias",
                            PhoneNumber = "288-543-7181"
                        },
                        new
                        {
                            Id = 90,
                            Email = "Ernestine@bataillonMail.com",
                            FirstName = "Ernestine",
                            LastName = "Clarehurst",
                            Level = 0,
                            NickName = "ErnestineAlias",
                            PhoneNumber = "626-772-2514"
                        },
                        new
                        {
                            Id = 91,
                            Email = "Marlon@bataillonMail.com",
                            FirstName = "Marlon",
                            LastName = "Lazmerge",
                            Level = 0,
                            NickName = "MarlonAlias",
                            PhoneNumber = "354-831-6127"
                        },
                        new
                        {
                            Id = 92,
                            Email = "Eugenie@bataillonMail.com",
                            FirstName = "Eugenie",
                            LastName = "Reidcoln",
                            Level = 0,
                            NickName = "EugenieAlias",
                            PhoneNumber = "771-268-2532"
                        },
                        new
                        {
                            Id = 93,
                            Email = "Cathryn@bataillonMail.com",
                            FirstName = "Cathryn",
                            LastName = "Breksos",
                            Level = 0,
                            NickName = "CathrynAlias",
                            PhoneNumber = "317-427-5145"
                        },
                        new
                        {
                            Id = 94,
                            Email = "Jamal@bataillonMail.com",
                            FirstName = "Jamal",
                            LastName = "Nuugaatrapaluk",
                            Level = 0,
                            NickName = "JamalAlias",
                            PhoneNumber = "744-566-1558"
                        },
                        new
                        {
                            Id = 95,
                            Email = "Emely@bataillonMail.com",
                            FirstName = "Emely",
                            LastName = "Norrviken",
                            Level = 0,
                            NickName = "EmelyAlias",
                            PhoneNumber = "362-715-4163"
                        },
                        new
                        {
                            Id = 96,
                            Email = "Tad@bataillonMail.com",
                            FirstName = "Tad",
                            LastName = "Eqalunavik",
                            Level = 0,
                            NickName = "TadAlias",
                            PhoneNumber = "887-154-8576"
                        },
                        new
                        {
                            Id = 97,
                            Email = "Steven@bataillonMail.com",
                            FirstName = "Steven",
                            LastName = "Ulhus",
                            Level = 0,
                            NickName = "StevenAlias",
                            PhoneNumber = "435-313-3181"
                        },
                        new
                        {
                            Id = 98,
                            Email = "Roma@bataillonMail.com",
                            FirstName = "Roma",
                            LastName = "Apatcruz",
                            Level = 0,
                            NickName = "RomaAlias",
                            PhoneNumber = "853-442-7514"
                        },
                        new
                        {
                            Id = 99,
                            Email = "Simonne@bataillonMail.com",
                            FirstName = "Simonne",
                            LastName = "Mõisali",
                            Level = 0,
                            NickName = "SimonneAlias",
                            PhoneNumber = "478-681-3127"
                        });
                });

            modelBuilder.Entity("LeBataillon.Database.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Captain")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Captain = 10,
                            TeamName = "Krissy"
                        },
                        new
                        {
                            Id = 2,
                            Captain = 20,
                            TeamName = "Pat"
                        },
                        new
                        {
                            Id = 3,
                            Captain = 30,
                            TeamName = "Palmira"
                        },
                        new
                        {
                            Id = 4,
                            Captain = 40,
                            TeamName = "Ralph"
                        },
                        new
                        {
                            Id = 5,
                            Captain = 50,
                            TeamName = "Arielle"
                        },
                        new
                        {
                            Id = 6,
                            Captain = 60,
                            TeamName = "Troy"
                        },
                        new
                        {
                            Id = 7,
                            Captain = 70,
                            TeamName = "Marcell"
                        },
                        new
                        {
                            Id = 8,
                            Captain = 80,
                            TeamName = "Vi"
                        },
                        new
                        {
                            Id = 9,
                            Captain = 90,
                            TeamName = "Sherise"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
